services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
        - app
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
        - app

  api-service:
    depends_on:
      - mongo
      - stock-service
    build: 
      context: .
      dockerfile: api.Dockerfile
    image: api-service
    container_name: api-service
    ports:
      - "${PORT_API}:${PORT_API}"
    environment:
      PORT: ${PORT_API}
      MONGO_URL: ${MONGO_URL}
      SECRET: ${SECRET}
      STOCKS_URL: ${STOCKS_URL}
      MAIL_SERVICE: ${MAIL_SERVICE}
      USER_EMAIL: ${USER_EMAIL}
      USER_EMAIL_PASSWORD: ${USER_EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      NODE_ENV: ${NODE_ENV}
    networks:
        - app

  stock-service:
    build: 
      context: .
      dockerfile: stock.Dockerfile
    image: stock-service
    container_name: stock-service
    environment:
      PORT: ${PORT_STOCK}
      STOCK_API_URL: ${STOCK_API_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
    networks:
        - app

networks:
  app:
    driver: bridge
